# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66266bdf32e75472ea62e98d37e652fe"
name = "judgeme"
application_url = "https://judge-me-sigma.vercel.app"
embedded = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://judge-me-sigma.vercel.app/auth/callback",
  "https://judge-me-sigma.vercel.app/api/auth"
]

[pos]
embedded = true

[build]
automatically_update_urls_on_dev = true
